## Artifical Neural Network

Kütüphanelerin içeri aktarılması

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

* Tensorflow version

In [2]:
tf.__version__

'2.15.0'

#### Veri Ön İşleme

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #3. kolondan başlayarak exited kolonuna kadar
Y = dataset.iloc[:, -1].values # Exited kolonu

In [5]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
Y

array([1, 0, 1, ..., 1, 1, 0])

#####  Encoding

* Cinsiyet için Label Encoding

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)  #Female = 0, Male = 1

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


* Ülke kolonu için One Hot Encoding

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X) #Fransa=100, İspanya=001, Almanya=010 olarak kodlandı

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


* Verinin test ve eğitim olarak bölünmesi

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

* Özellik Ölçeklemesi


> Derin Öğrenme için yapılması zorunludur.



In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# ANN'yi İnşa Etme

* Sıralı yapay sinir ağı

In [13]:
ann = tf.keras.models.Sequential()

* İlk gizli katmanın(Hidden Layer) eklenmesi

>Kaç tane gizli nörona sahip olmak istiyorsak "units=" parametresinde belirtmemiz gerekiyor.


>Aktivasyon fonksiyonuna ("activation=")
karşılık gelen değer hariç tümü için aynı değerler korunur.




In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

* İkinci gizli katmanın eklenmesi


>İkinci gizli katmanın eklenmesi, ilk gizli katmanın eklenmesi ile aynıdır.
  >> !! Eğer nöron sayısı sabit olacaksa


In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

* Çıktı katmanının (Output Layer) eklenmesi

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

* ANN'yi Derleme


> İkili bir sonucu tahmin ederken her zaman `loss=binary_crossentropy` olmalıdır.



In [17]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

* ANN'nin eğitim seti üzerinde eğitilmesi

In [18]:
ann.fit(X_train, y_train, batch_size=32, epochs=20)

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 0.7695 - accuracy: 0.5378
Epoch 2/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4831 - accuracy: 0.8096
Epoch 3/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4441 - accuracy: 0.8176
Epoch 4/20
250/250 [==============================] - 1s 2ms/step - loss: 0.4234 - accuracy: 0.8241
Epoch 5/20
250/250 [==============================] - 1s 2ms/step - loss: 0.4076 - accuracy: 0.8319
Epoch 6/20
250/250 [==============================] - 1s 2ms/step - loss: 0.3920 - accuracy: 0.8393
Epoch 7/20
250/250 [==============================] - 1s 2ms/step - loss: 0.3781 - accuracy: 0.8472
Epoch 8/20
250/250 [==============================] - 1s 2ms/step - loss: 0.3673 - accuracy: 0.8487
Epoch 9/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3605 - accuracy: 0.8545
Epoch 10/20
250/250 [==============================] - 0s 2ms/step - loss: 0.3563 - accuracy: 0.8559

# SONUÇLAR
* "accuracy" metriğine göre model %86 doğruluk değerine sahiptir.
* Parametreler değiştirilerek/düzeltilerek doğruluk oranı artırabilir.

# **Örnek**

ANN'yi kullanarak aşağıdaki özelliklere sahip olan müşterinin bankadan ayrılıp ayrılmayacağını tahmin et.

* Geography: France
* Credit Score: 600
* Gender: Male
* Age: 40 years old
* Tenure: 3 years
* Balance: $ 60000

* Number of products: 2
* Kredi kartına sahip mi?: Yes
* Aktif bir üye mi?: Yes
* Estimated Salary: $ 50000


In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 30ms/step
[[False]]


* ANN'yi ölçeklendirdiğimiz için ```sc.transform``` kullanılmalıdır.



* Label Encoding aşamasıdan Fransa: [1,0,0] olarak kodlanmıştı

* Label Encoding aşamasında Male: 1 olarak kodlanmıştı

* Kredi kartına sahip mi? Label Encoding aşamasında 1 olarak kodlanmıştı

* Aktif bir üye mi? Label Encoding aşamasında 1 olarak kodlanmıştı

------------------------------------------

Tahmin ve Test Seti Sonuçları
* Sol sütun yapay sinir ağının tahminleri
* Sağ sütun gerçek sonuçlar

In [22]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)), 1))

63/63 [==============================] - 0s 4ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Confusion Matrix

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1529   66]
 [ 212  193]]


0.861